server:
    port: ${port:0}

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost
        instance-id:
            ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            routes:
                - id: category-service
                  uri: lb://category-service
                  predicates:
                    - Path=/api/cate/*
                    - Query=categoryId
                  filters:
                    - StripPrefix=2
                

